# Generated by Django 4.2.2 on 2023-07-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ALTERNATIVE', 'Alternative')], default='Proposed', max_length=20)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('approval_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_approve_votes', models.PositiveIntegerField(default=0)),
                ('total_reject_votes', models.PositiveIntegerField(default=0)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=True)),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ALTERNATIVE', 'Alternative')], default='Proposed', max_length=20)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('approval_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_approve_votes', models.PositiveIntegerField(default=0)),
                ('total_reject_votes', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(to='app01.keyword')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.questiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ALTERNATIVE', 'Alternative')], default='Proposed', max_length=20)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('approval_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_approve_votes', models.PositiveIntegerField(default=0)),
                ('total_reject_votes', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('BINARY', 'BINARY'), ('SCALE_DECIMAL', 'SCALE_DECIMAL'), ('SCALE_INT', 'SCALE_INT')], default='BINARY', max_length=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.question')),
                ('question_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app01.questiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyWordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ALTERNATIVE', 'Alternative')], default='Proposed', max_length=20)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('approval_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_approve_votes', models.PositiveIntegerField(default=0)),
                ('total_reject_votes', models.PositiveIntegerField(default=0)),
                ('definition', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keyword', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='app01.keyword')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.keyworddefinition')),
                ('questions', models.ManyToManyField(related_name='keyword_definitions', to='app01.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ALTERNATIVE', 'Alternative')], default='Proposed', max_length=20)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('approval_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_approve_votes', models.PositiveIntegerField(default=0)),
                ('total_reject_votes', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.answerbinary')),
                ('question_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_tag', to='app01.questiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votable_object_id', models.PositiveIntegerField()),
                ('vote', models.IntegerField(choices=[(1, 'APPROVE'), (-1, 'REJECT'), (0, 'NO_VOTE')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votable_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('user', 'votable_content_type', 'votable_object_id')},
            },
        ),
    ]
