# Generated by Django 4.2.1 on 2023-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
