# Generated by Django 4.2.2 on 2023-06-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='keywords',
            field=models.ManyToManyField(to='app01.keyword'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tags', to='app01.questiontag'),
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='keyword',
        ),
    ]
