# Generated by Django 4.2.2 on 2023-06-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_questiontag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent_question',
        ),
        migrations.AddField(
            model_name='keyword',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.keyword'),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.keyworddefinition'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.questiontag'),
        ),
    ]
