# Generated by Django 4.2.2 on 2023-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_question_parent_question_keyword_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='keyword',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='questions',
            field=models.ManyToManyField(related_name='keyword_definitions', to='app01.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyworddefinition',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
    ]
