# Generated by Django 4.2.1 on 2023-06-12 11:00

import app01.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0003_question_tag_useranswer_question_additional_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[(app01.models.InputType['YES_NO'], 'Yes / No'), (app01.models.InputType['SCALE_FLOAT'], 'Scale (floating point)'), (app01.models.InputType['SCALE_INT'], 'Scale (integer)')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProposedKeywordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_definition', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.keyworddefinition')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(related_name='questions', to='app01.keyworddefinition'),
        ),
    ]
