# Generated by Django 4.2.2 on 2023-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_keyword_approval_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='total_approve_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='total_reject_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='total_approve_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='total_reject_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyworddefinition',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_approve_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_reject_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='total_approve_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='total_reject_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
