# Generated by Django 4.2.1 on 2023-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_keyworddefinition_alter_question_input_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('YES_NO', 'Yes / No'), ('SCALE_FLOAT', 'Scale (floating point)'), ('SCALE_INT', 'Scale (integer)')], max_length=30),
        ),
    ]
