# Generated by Django 4.2.2 on 2023-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_keyword_status_alter_keyworddefinition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyworddefinition',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'proposed'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('ALTERNATIVE', 'alternative')], default='proposed', max_length=20),
        ),
    ]
