# Generated by Django 4.2.2 on 2023-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_keyword_status_alter_keyworddefinition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='keyworddefinition',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='keyworddefinition',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='approval_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='participation_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
