# Generated by Django 4.2.2 on 2023-07-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_keyword_status_alter_keyworddefinition_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontag',
            name='parent_tag',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app01.questiontag'),
        ),
    ]
